name: skin-effect-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy>=1.20.0
  - scipy>=1.7.0
  - matplotlib>=3.5.0
  - pandas>=1.3.0
  - jupyter>=1.0.0
  - jupyterlab>=3.0.0
  - ipywidgets>=7.6.0
  - pytest>=6.0.0
  - pytest-cov>=2.12.0
  - sphinx>=4.0.0
  - sphinx_rtd_theme>=1.0.0
  - pip
  - pip:
    - -e . 